// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"banking-system/transaction-service/rpc/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:   "/transfermoney",
				Handler: TransferMoneyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:   "/gettransactionhistory",
				Handler: GetTransactionHistoryHandler(serverCtx),
			},
		},
	)
}
