// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: transaction_api.proto

package server

import (
	"context"

	"banking-system/transaction-service/rpc/internal/logic"
	"banking-system/transaction-service/rpc/internal/svc"
	"banking-system/transaction-service/rpc/types/transaction/v1alpha1"
)

type TransactionAPIServiceServer struct {
	svcCtx *svc.ServiceContext
	v1alpha1.UnimplementedTransactionAPIServiceServer
}

func NewTransactionAPIServiceServer(svcCtx *svc.ServiceContext) *TransactionAPIServiceServer {
	return &TransactionAPIServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TransactionAPIServiceServer) TransferMoney(ctx context.Context, in *v1alpha1.TransferMoneyRequest) (*v1alpha1.TransferMoneyResponse, error) {
	l := logic.NewTransferMoneyLogic(ctx, s.svcCtx)
	return l.TransferMoney(in)
}

func (s *TransactionAPIServiceServer) GetTransactionHistory(ctx context.Context, in *v1alpha1.GetTransactionHistoryRequest) (*v1alpha1.GetTransactionHistoryResponse, error) {
	l := logic.NewGetTransactionHistoryLogic(ctx, s.svcCtx)
	return l.GetTransactionHistory(in)
}
