global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - "localhost:8125"
          - "localhost:9200"
          - "localhost:8081"
          - "transaction-service:50055"