version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    restart: always
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge