apiVersion: v1
kind: Secret
metadata:
  name: banking-service-secret
  namespace: develop
type: Opaque
stringData:
  NAME_SERVICE: 'banking-service'
  PORT: '8080'
  MONGODB_URI: 'mongodb://localhost:27017/'
  MONGODB_DB_NAME: 'account-service'
  JWT_SECRET: 'banking-service'
  JWT_EXPIRES_IN: '1d'
  EVENT_BROKERS: 'kafka-cluster-kafka-bootstrap:9091,kafka-cluster-kafka-bootstrap:9092'
  CREATE_ACCOUNT_TOPIC: 'account-events'
  ACCOUNT_GROUP: 'account-service'
  ACCOUNT_TOPIC_CONCURRENCY: '1'
