apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secret
  namespace: develop
type: Opaque
stringData:
  NAME_SERVICE: 'transaction-service'
  PORT: '8080'
  MONGODB_URI: 'mongodb://localhost:27017/'
  MONGODB_DB_NAME: 'transaction-service'
  JWT_SECRET: 'banking-service'
  JWT_EXPIRES_IN: '1d'
  EVENT_BROKERS: 'kafka-cluster-kafka-bootstrap:9091,kafka-cluster-kafka-bootstrap:9092'
  CREATE_TRANSACTION_TOPIC: 'transaction-events'
  TRANSACTION_GROUP: 'transaction-group'
  TRANSACTION_TOPIC_CONCURRENCY: '1'
